name: Exercise_02_CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    env:
      APP_DB_USERNAME: "postgres"
      APP_DB_PASSWORD: "geheim"
      APP_DB_NAME: "pg_database"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
