
name: Ex_04 build and test

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test_Ex04
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.11
        uses: actions/setup-go@v2
        with:
          go-version: ^1.11
        id: go

      - name: Check code
        uses: actions/checkout@v2

      - name: Test_Ex04 go test -v
        run: go test -v .
  

  buildAndPush:
    name: DockerHub build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: Build image 
        run: docker build -t cbachl/demo:latest .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cbachl/demo:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Declare commmit hash variable
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cbachl/demo:latest, cbachl/demo:${{ steps.vars.outputs.sha_short }}
      

